### ISSUE TITLE
Enabling reroute asks session password 3 times

### ISSUE THREAD

**Issue by jchatard** [chetan51/sidestep#35] opened 2011-12-14 16:41 UTC
I don't know if this specific to my setup, but when I enable the _Reroute Traffic Through Proxy Server Now_ Lion asks me my user session password 3 times before actually rerouting.

Any solution to reduce or remove this requirement?

I don't know if this could be related by the built-in Firewall is activated.

**Comment by chetan51** [comment] 2011-12-24 02:25
Try setting up passwordless login (http://burnz.wordpress.com/2007/10/17/sshssh2-password-less-authentication/).

**Comment by jchatard** [comment] 2011-12-24 03:18
No luck, I can login without password from the terminal, but still asked 3 times  for my OS X session password when re-routing traffic. It is asked by `networksetup` (is trying to modify your system settings...)

**Comment by chetan51** [comment] 2011-12-24 04:24
I've seen this before, but I'm not sure how to get around it. Sorry! Please update this issue if you figure out a workaround.

**Comment by jchatard** [comment] 2012-02-17 06:20
After upgrading to OS X 10.7.3 (11D50b) I'm not asked any password anymore.

**Comment by chetan51** [comment] 2012-02-17 06:35
Weird, but I guess that's a good thing!

**Comment by JJJ** [comment] 2012-06-21 03:37
This is back after an update to Mountain Lion, using Sidestep 1.3.1.

**Comment by chetan51** [comment] 2012-06-21 20:48
Try opening System Preferences > Network, and then click the lock on the bottom left corner of the window to make sure it's unlocked. Let me know if that fixes the problem or not.

**Comment by JJJ** [comment] 2012-06-26 02:47
No change. The same prompt also appears (once, rather than 3 times) when turning off Sidestep, and when Sidestep launches for the first time (on boot.)

**Comment by asenchi** [comment] 2012-06-30 09:02
I also have this issue on Lion (latest patch).

**Comment by markjaquith** [comment] 2012-07-16 23:14
Screenshot of the issue in OS X 10.8 Mountain Lion.

![](http://cl.ly/image/2L3T2h1y0R3Y/Screen%20Shot%202012-07-16%20at%207.09.51%20PM.png)

Details:
- Sidestep 1.3.1
- The padlock in Network Settings is **unlocked** (changing this has no effect)
- The prompt comes up **once** when starting Sidestep
- The prompt comes up **three** times when rerouting through a proxy
- The prompt comes up **once** when restoring a direct connection

**Comment by chetan51** [comment] 2012-07-22 02:19
Figured out the cause of this problem: The `networksetup` command and the `airport` command in Mountain Lion must be run as root. So when Sidestep tries to run shell scripts that call those commands to check the network status and change the proxy settings, those password prompts come up.

So basically, these annoying prompts are due to Mountain Lion's more stringent security policies. From what I've seen so far, getting around this won't be an easy matter. I'll keep looking.

**Comment by asenchi** [comment] 2012-07-22 11:33
I suspect the same is true for Lion, since I have the issue there as well.

**Comment by justinmayer** [comment] 2012-07-30 14:33
The same problem appeared for me after the upgrade to 10.8, and the incessant triplicate dialogs are cumbersome enough for me to disable Sidestep until a workaround has been found. Any progress in resolving this issue?

**Comment by Dhutz** [comment] 2012-07-30 23:07
I just went to a Genius bar and called Apple care.  Couldn't have been more useless.

**Comment by sydneystufff** [comment] 2012-07-31 09:15
I am having the very same issue, as markjaquith above: "Screenshot of the issue in OS X 10.8 Mountain Lion". 

My issue is when using my Telstra 4G USB modem. 

When connecting, I need to authenticate 3 times - very annoying. If I select cancel, I can connect but the internet fails to be usable.

I have tried as above, nothing stops it...

**Comment by hannesgassert** [comment] 2012-08-05 16:50
+1

**Comment by hannesgassert** [comment] 2012-08-05 17:03
`sudo chmod +s /usr/sbin/networksetup` is not nice, not even as a workaround, but looks like it gets rid of the password prompts.

An actual solution problem is something like https://github.com/jerrykrinock/AuthorizedTasksInCocoa, which sounds painful indeed.

**Comment by dgomes** [comment] 2012-08-08 18:25
My patch actually only fixes the ProxtSetter... but the same logic can be re-applied to the other classes.

**Closed as completed** 2012-11-06 22:31 UTC
