### ISSUE TITLE
Sidestep doesn't toggle SOCKS setting in Network Prefs under Mavericks DP3

### ISSUE THREAD

**Issue by ryanmarkel** [chetan51/sidestep#59] opened 2013-07-09 17:54 UTC
Sidestep will configure the SSH tunnel when used in Mavericks Developer Preview 3, but it doesn't appear to switch over the SOCKS proxy setting in Network Preferences - I have to toggle that manually to use the proxy.

**Comment by joehoyle** [comment] 2013-07-24 05:30
+1 would be great to get this working

**Comment by lukeman** [comment] 2013-07-26 08:19
I'm not sure this is isolated to Mavericks. See #49 and #55 for at least two duplicate reports on multiple versions.

**Comment by nickgernert** [comment] 2013-10-23 12:54
Confirmed I am seeing the same behavior in the release version of 10.9

**Comment by dgomes** [comment] 2013-10-23 13:19
I just got Mavericks on my laptop, I’ll look into this during the weekend (hopefully)

= Diogo Gomes
http://about.me/dgomes

**Comment by macbentosh** [comment] 2013-10-24 18:41
so how does one get this updated version?

**Comment by chetan51** [comment] 2013-10-24 18:49
I've already merged in the pull request. I'll release an update soon. If
you need it sooner than that, you can pull the latest code and create your
own build with Xcode.

**Closed as completed by chetan51** 2013-10-24 18:49 UTC

**Comment by macbentosh** [comment] 2013-10-24 18:52
Great Thanks! I built in in Xcode and look forward to the release!! Thanks for the quick work on this!

**Comment by isaackeyet** [comment] 2013-10-26 02:47
Can't wait to have the update, have been clicking the Check for Updates button like a mad man since Mavericks!

**Comment by chetan51** [comment] 2013-10-26 02:47
I've released it!

**Comment by isaackeyet** [comment] 2013-10-26 03:07
Ohh, shiny! Thanks so much, works perfectly now.

**Comment by chetan51** [comment] 2013-10-26 03:46
Thanks to Diogo for all the work!

**Comment by dgomes** [comment] 2013-10-26 11:09
Your welcome ;)

= Diogo Gomes
http://about.me/dgomes

**Comment by nickgernert** [comment] 2013-10-26 18:12
Thanks @dgomes - updated to 1.4.1 on OSX 10.9 and things work perfectly.
